In [48]:
%matplotlib inline
import numpy as np
import scipy
import scipy.io as spio
import matplotlib.pyplot as plt
from PIL import Image
import glob
import os
from collections import Counter
from sklearn.cross_validation import train_test_split

In [49]:
import tables
file = tables.openFile('annotations.mat')
print (file)
a= file['class']
print (a)

#class = file.root.class[:]

ImportError: No module named 'tables'

In [54]:
file = open('class.txt', 'r')
print file.readline()



SyntaxError: invalid syntax (<ipython-input-54-bafa55dcaebc>, line 2)

In [5]:

c = mat['annotations']
d = c['relative_im_path']
print (d)

[[array(['car_ims/000001.jpg'], 
      dtype='<U18')
  array(['car_ims/000002.jpg'], 
      dtype='<U18')
  array(['car_ims/000003.jpg'], 
      dtype='<U18') ...,
  array(['car_ims/016183.jpg'], 
      dtype='<U18')
  array(['car_ims/016184.jpg'], 
      dtype='<U18')
  array(['car_ims/016185.jpg'], 
      dtype='<U18')]]


In [34]:
from scipy import stats
a= c['class']
print (a)
#a=np.array(a)
#a.tolist()
#print (a[:1])
a=a.astype(np.int)
print(a) 
print (len(a))
a.dtype

#stats.describe(a)
#from itertools import groupby
#[len(list(group)) for key, group in groupby(label)]

[[array([[1]], dtype=uint8) array([[1]], dtype=uint8)
  array([[1]], dtype=uint8) ..., array([[196]], dtype=uint8)
  array([[196]], dtype=uint8) array([[196]], dtype=uint8)]]
[[  1   1   1 ..., 196 196 196]]
1


dtype('int64')

In [39]:
for field in c['class']:
    # getattr will return the value for the given key
    print (c['class'] )


[[array([[1]], dtype=uint8) array([[1]], dtype=uint8)
  array([[1]], dtype=uint8) ..., array([[196]], dtype=uint8)
  array([[196]], dtype=uint8) array([[196]], dtype=uint8)]]


In [23]:

#a = [1,1,1,1,2,2,2,2,3,3,4,5,5]
#counter=collections.Counter(a)
#d = {x:a.count(x) for x in a}
e=Counter(a)
c.values()


TypeError: unhashable type: 'numpy.ndarray'